<?php

namespace ContainerNxokBej;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIniciativaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\IniciativaController' shared autowired service.
     *
     * @return \App\Controller\IniciativaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/IniciativaController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/IniciativaService.php';

        $container->services['App\\Controller\\IniciativaController'] = $instance = new \App\Controller\IniciativaController(new \App\Service\IniciativaService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\INICIATIVASRepository'] ?? $container->load('getINICIATIVASRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\IniciativaController', $container));

        return $instance;
    }
}
