<?php

namespace ContainerNxokBej;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModulosControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ModulosController' shared autowired service.
     *
     * @return \App\Controller\ModulosController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ModulosController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ModulosService.php';

        $container->services['App\\Controller\\ModulosController'] = $instance = new \App\Controller\ModulosController(new \App\Service\ModulosService(($container->privates['App\\Repository\\MODULOSRepository'] ?? $container->load('getMODULOSRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\ModulosController', $container));

        return $instance;
    }
}
