<?php

namespace ContainerNxokBej;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getODSControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ODSController' shared autowired service.
     *
     * @return \App\Controller\ODSController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ODSController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ODSService.php';

        $container->services['App\\Controller\\ODSController'] = $instance = new \App\Controller\ODSController(new \App\Service\ODSService(($container->privates['App\\Repository\\ODSRepository'] ?? $container->load('getODSRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\ODSController', $container));

        return $instance;
    }
}
