<?php

namespace Container77vfSpX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDimensionesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DimensionesController' shared autowired service.
     *
     * @return \App\Controller\DimensionesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DimensionesController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DimensionesService.php';

        $container->services['App\\Controller\\DimensionesController'] = $instance = new \App\Controller\DimensionesController(new \App\Service\DimensionesService(($container->privates['App\\Repository\\DimensionRepository'] ?? $container->load('getDimensionRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\DimensionesController', $container));

        return $instance;
    }
}
