<?php

namespace Container77vfSpX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetasControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MetasController' shared autowired service.
     *
     * @return \App\Controller\MetasController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MetasController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MetasService.php';

        $container->services['App\\Controller\\MetasController'] = $instance = new \App\Controller\MetasController(new \App\Service\MetasService(($container->privates['App\\Repository\\MetaRepository'] ?? $container->load('getMetaRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\MetasController', $container));

        return $instance;
    }
}
